### ISSUE TITLE
Open Source License?

### ISSUE THREAD

**Issue by spicydll** [jkrshnmenon/arbiter#15]
I noticed this repository is missing a LICENSE file. I want to use this software as part of a project I'm developing. However, I legally cannot unless a compatible license is applied.

If this project is intended to be open source, please apply a license to make it so, such as the MIT license.

Thanks!

**Comment by adamdoupe** [comment]
Thanks for letting us know, we forgot to slap a license on the repo. We’ll
get to it as soon as we decide on which one.

- Adam Doupé

**Comment by spicydll** [comment]
Thank you so much!

**Comment by jkrshnmenon** [comment]
Thanks for pointing this out.
We've added a [LICENSE](https://github.com/jkrshnmenon/arbiter/blob/master/LICENSE) file now.
