### ISSUE TITLE
vuln_templates is not in the Docker file

### ISSUE THREAD

**Issue by y3noor** [jkrshnmenon/arbiter#8]
Hi, 
while in Dockerfile I see you have copied vuln_templates folder, after pulling the docker image there is not such file in /home/test

**Comment by jkrshnmenon** [comment]
The docker image on dockerhub has not been updated with the latest code. I'm working on some changes right now and will update the image after they've been tested.

**Comment by jkrshnmenon** [comment]
Update, the docker image should now be similar to the latest code.
